#!/bin/bash

keyfile=$1
infile=$2
outfile=$3

if [ -z $keyfile ]; then
    echo "usage: decrypt <keyfile> [infile] [outfile]"
    exit 1
fi

key=$(cat $keyfile | head -c 64)
iv=$(cat $keyfile | tail -c 32)

if [ ! -z $outfile ]; then
    openssl aes-256-cbc -d -K $key -iv $iv -in $infile -out $outfile
else
    openssl aes-256-cbc -d -K $key -iv $iv
fi
