#!/bin/bash

file=$1

if [ -z $file ]; then
    echo "usage: keygen <file>"
    exit 1
fi
if [ -f $file ]; then
    echo "file already exists: $file"
    exit 1
fi

tr -dc '0-9a-f' < /dev/urandom | head -c 96 > $file