#!/bin/bash

file=$1
m=$2
n=$3

if [ -z $file ] || [ -z $m ] || [ -z $n ]; then
    echo "usage: keysplit <file> <threshold> <shares>"
    exit 1
fi

cat $file | ssss-split -t $m -n $n -Q | split -a 1 -l 1 --numeric-suffixes=1 - $file.