#!/bin/bash

file=$1
threshold=$2

if [ -z $file ] || [ -z $threshold ]; then
    echo "usage: keymerge <file> <threshold>"
    exit 1
fi
if [ -f $file ]; then
    echo "output file already exists: $file"
    exit 1
fi

cat $file.* | ssss-combine -t $threshold -q > $file
